// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function BinaryName():Promise<string>;

export function ClaudeConfig():Promise<string>;

export function ClearLogs():Promise<void>;

export function DefaultSSHKey():Promise<string>;

export function DeleteCluster(arg1:string):Promise<void>;

export function DeleteSource(arg1:string):Promise<void>;

export function DeleteWriteUser(arg1:string):Promise<void>;

export function DiagnoseServer(arg1:model.Source):Promise<Array<model.CheckResult>>;

export function EnableSource(arg1:model.Source,arg2:Array<model.CheckResult>):Promise<model.Source>;

export function ExecWrite(arg1:string,arg2:string,arg3:boolean):Promise<model.WriteResult>;

export function FleetOverview():Promise<model.FleetOverview>;

export function GenerateManualScript(arg1:model.Source,arg2:string,arg3:string):Promise<string>;

export function GenerateProvisionSQL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetDoctor(arg1:string):Promise<Array<model.DoctorFinding>>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetSchema(arg1:string):Promise<model.SchemaInfo>;

export function GetSettings():Promise<Record<string, string>>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string):Promise<Array<model.ColumnInfo>>;

export function HasWriteUser(arg1:string):Promise<boolean>;

export function ListClusters():Promise<Array<model.Cluster>>;

export function ListSources():Promise<Array<model.Source>>;

export function LogPath():Promise<string>;

export function MCPConfig():Promise<string>;

export function MCPStatus():Promise<Record<string, any>>;

export function MCPToolsPreview():Promise<string>;

export function NewAIPassword():Promise<string>;

export function OpencodeConfig():Promise<string>;

export function PickSQLiteFile():Promise<string>;

export function PickSSHKey():Promise<string>;

export function PreviewTable(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:Array<model.Filter>,arg7:string):Promise<model.QueryResult>;

export function ProvisionAIUser(arg1:main.ProvisionRequest):Promise<Array<model.CheckResult>>;

export function ReverifySource(arg1:string):Promise<Array<model.CheckResult>>;

export function RunQuery(arg1:string,arg2:string):Promise<model.QueryResult>;

export function SampleTable(arg1:string,arg2:string,arg3:string):Promise<model.QueryResult>;

export function SaveCluster(arg1:model.Cluster):Promise<model.Cluster>;

export function SaveSource(arg1:model.Source):Promise<model.Source>;

export function SaveWriteUser(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetWriteMode(arg1:boolean):Promise<void>;

export function StartMCP():Promise<string>;

export function StorePath():Promise<string>;

export function TestAdminConnection(arg1:main.AdminTestRequest):Promise<Array<model.CheckResult>>;

export function TestConnection(arg1:main.TestRequest):Promise<Array<model.CheckResult>>;

export function TestMCP():Promise<string>;

export function TestSSH(arg1:model.Source):Promise<string>;

export function TestSSHByID(arg1:string):Promise<string>;

export function Version():Promise<string>;

export function WriteMode():Promise<boolean>;

export function WriteUserName(arg1:string):Promise<string>;
