// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BinaryName() {
  return window['go']['main']['App']['BinaryName']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClaudeConfig() {
  return window['go']['main']['App']['ClaudeConfig']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DefaultSSHKey() {
  return window['go']['main']['App']['DefaultSSHKey']();
}

export function DeleteCluster(arg1) {
  return window['go']['main']['App']['DeleteCluster'](arg1);
}

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function DeleteWriteUser(arg1) {
  return window['go']['main']['App']['DeleteWriteUser'](arg1);
}

export function DiagnoseServer(arg1) {
  return window['go']['main']['App']['DiagnoseServer'](arg1);
}

export function DownloadAndInstallUpdate() {
  return window['go']['main']['App']['DownloadAndInstallUpdate']();
}

export function EnableSource(arg1, arg2) {
  return window['go']['main']['App']['EnableSource'](arg1, arg2);
}

export function ExecWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecWrite'](arg1, arg2, arg3);
}

export function FleetOverview() {
  return window['go']['main']['App']['FleetOverview']();
}

export function GenerateManualScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateManualScript'](arg1, arg2, arg3);
}

export function GenerateProvisionSQL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateProvisionSQL'](arg1, arg2, arg3, arg4);
}

export function GetDoctor(arg1) {
  return window['go']['main']['App']['GetDoctor'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetSchema(arg1) {
  return window['go']['main']['App']['GetSchema'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTableColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3);
}

export function HasWriteUser(arg1) {
  return window['go']['main']['App']['HasWriteUser'](arg1);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function ListSources() {
  return window['go']['main']['App']['ListSources']();
}

export function LogPath() {
  return window['go']['main']['App']['LogPath']();
}

export function MCPConfig() {
  return window['go']['main']['App']['MCPConfig']();
}

export function MCPStatus() {
  return window['go']['main']['App']['MCPStatus']();
}

export function MCPToolsPreview() {
  return window['go']['main']['App']['MCPToolsPreview']();
}

export function NewAIPassword() {
  return window['go']['main']['App']['NewAIPassword']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function OpencodeConfig() {
  return window['go']['main']['App']['OpencodeConfig']();
}

export function PickSQLiteFile() {
  return window['go']['main']['App']['PickSQLiteFile']();
}

export function PickSSHKey() {
  return window['go']['main']['App']['PickSSHKey']();
}

export function PreviewTable(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['PreviewTable'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ProvisionAIUser(arg1) {
  return window['go']['main']['App']['ProvisionAIUser'](arg1);
}

export function ReverifySource(arg1) {
  return window['go']['main']['App']['ReverifySource'](arg1);
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2);
}

export function SampleTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SampleTable'](arg1, arg2, arg3);
}

export function SaveCluster(arg1) {
  return window['go']['main']['App']['SaveCluster'](arg1);
}

export function SaveSource(arg1) {
  return window['go']['main']['App']['SaveSource'](arg1);
}

export function SaveWriteUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWriteUser'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetWriteMode(arg1) {
  return window['go']['main']['App']['SetWriteMode'](arg1);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['App']['SkipUpdateVersion'](arg1);
}

export function StartMCP() {
  return window['go']['main']['App']['StartMCP']();
}

export function StorePath() {
  return window['go']['main']['App']['StorePath']();
}

export function TestAdminConnection(arg1) {
  return window['go']['main']['App']['TestAdminConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestMCP() {
  return window['go']['main']['App']['TestMCP']();
}

export function TestSSH(arg1) {
  return window['go']['main']['App']['TestSSH'](arg1);
}

export function TestSSHByID(arg1) {
  return window['go']['main']['App']['TestSSHByID'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WriteMode() {
  return window['go']['main']['App']['WriteMode']();
}

export function WriteUserName(arg1) {
  return window['go']['main']['App']['WriteUserName'](arg1);
}
